# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import mahasiswa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[mahasiswa.models.validate_not_spaces])),
                ('nama', models.CharField(max_length=100, validators=[mahasiswa.models.validate_not_spaces])),
                ('alamat', models.CharField(max_length=100, validators=[mahasiswa.models.validate_not_spaces])),
                ('no_telp', models.CharField(blank=True, default='', max_length=13)),
                ('stat', models.CharField(max_length=2, validators=[mahasiswa.models.validate_not_spaces])),
                ('gender', models.CharField(max_length=1, validators=[mahasiswa.models.validate_not_spaces])),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('agama', models.CharField(max_length=20, validators=[mahasiswa.models.validate_not_spaces])),
                ('dob', models.CharField(max_length=10, validators=[mahasiswa.models.validate_not_spaces])),
                ('pwd', models.CharField(max_length=12, validators=[mahasiswa.models.validate_not_spaces])),
                ('en_pwd', models.CharField(max_length=255)),
            ],
        ),
    ]
