# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_auto_20171227_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='en_pwd',
            field=models.CharField(max_length=255),
        ),
    ]
